import PDFDocument from 'pdfkit';

interface FleetPartnerAgreementData {
  carId: string;
  createdAt: Date;
  ownerName: string;
  ownerEmail: string;
  ownerPhone: string;
  fleetOperatorName: string;
  fleetOperatorEmail: string;
  fleetOperatorPhone: string;
  make: string;
  model: string;
  year: number;
  registrationNo: string;
  chassisNo?: string | null;
  transmission: string;
  fuelType: string;
  hasComprehensiveInsurance: boolean;
}

const WEAR_AND_TEAR_EXCLUSIONS = [
  'AC evaporator damage', 'AC noise / smell / low cooling / not working', 'Accessories fitment issue',
  'Battery discharge / not working', 'Black smoke emission from exhaust', 'Cameras/sensors not working',
  'Damage in pumps (oil / water / fuel)', 'Drive belt damage', 'Electrical malfunctions (windows/lights/instrumentation etc)',
  'Engine vibrations', 'Filters blocked or not working (AC / air / fuel)', 'Floor mats damage',
  'Fuel level indicator not functioning', 'Hairline/minor scratches', 'Hardness of steering wheel or pedals (brake/clutch/accelerator)',
  'Headlight height adjuster damage', 'Headrest or seatbelts not working', 'High fuel consumption',
  'Horn not working', 'Injectors damage', 'Key cylinder not engaging', 'Lights not working (head/tail/indicator/interior)',
  'Low fluid levels (engine oil / coolant / brake fluid / other lubricants)', 'Low handbrake efficiency', 'Low pickup',
  'Noise in brakes / clutch / gears / engine / suspension / axle', 'Noise in doors / panels / dashboard elements / wheels / tyres / seat rack',
  'Poor braking', 'Radiator fan low cooling', 'Rain wipers/sensor issue',
  'Replacement of consumables (clutch / brake components, fluids, filters)', 'Side mirrors (ORVM) malfunctions',
  'Speakers or infotainment system not working', 'Starting issue', 'Tensioner pulley noise', 'Timing belt damage',
  'Tyre air leaks / low pressure / bubbles / punctures / worn out', 'Vehicle pulling left/right; tyres wobbling',
  'Water ingress through doors/roof/pillars',
];

const DEEMED_VALUE_TABLE: [string, string][] = [
  ['Under 1 year', '80%'], ['1–2 years', '70%'], ['2–3 years', '62%'], ['3–4 years', '54%'],
  ['4–5 years', '46%'], ['5–6 years', '39%'], ['6–7 years', '32%'], ['7–8 years', '25%'],
];

/** Renders the real, ground-truthed Fleet Partner Agreement (genericized from executed reference contracts) as a PDF buffer for Setu eSign upload. */
export function renderFleetPartnerAgreementPdf(data: FleetPartnerAgreementData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const h1 = () => doc.font('Helvetica-Bold').fontSize(12).moveDown(0.3);
    const body = () => doc.font('Helvetica').fontSize(10.5);
    const bullet = (text: string) => body().text(`•  ${text}`, { indent: 10 });

    doc.font('Helvetica-Bold').fontSize(15).text('VEHICLE LEASING/SHARING AND', { align: 'center' });
    doc.text('MULTI-PLATFORM SERVICES AGREEMENT', { align: 'center' });
    doc.font('Helvetica').fontSize(9).fillColor('#666').text('Eightlines Fleet Private Limited — Fleet Partner Agreement', { align: 'center' });
    doc.fontSize(8).fillColor('#888').text(`Agreement ID: FPA-${data.carId.slice(0, 8).toUpperCase()}`, { align: 'center' });
    doc.moveDown(1).fillColor('#000');

    doc.fontSize(8.5).font('Helvetica-Oblique').fillColor('#555').text(
      'This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder ' +
      'as applicable. This electronic record is generated by a computer system and does not require physical signatures.'
    );
    doc.moveDown(0.8).fillColor('#000').fontSize(10.5).font('Helvetica');

    doc.text(`This Agreement is entered on ${data.createdAt.toLocaleDateString('en-IN')} ("Agreement Date").`);
    doc.moveDown(0.6);

    doc.font('Helvetica-Bold').text('BY AND BETWEEN', { align: 'center' });
    body().text(
      `${data.ownerName} (hereinafter referred to as the "Owner", which expression shall, unless repugnant to the ` +
      `context, mean and include their successors, legal heirs, and permitted assignees) of the FIRST PART;`
    );
    doc.moveDown(0.3);
    doc.font('Helvetica-Bold').text('AND', { align: 'center' });
    body().text(
      'Eightlines Fleet Private Limited, a private limited company incorporated under the Companies Act, 2013, ' +
      'bearing Corporate Identification Number (CIN) U77100KA2026PTC7772 and having its registered office at ' +
      '8-Lines Fleet, 15th Cross Rd, Popular Colony, Mangammanapalya, Bengaluru, Karnataka 560068, represented by ' +
      `its authorized fleet operator ${data.fleetOperatorName} (hereinafter referred to as "Eightlines", which ` +
      'expression shall unless repugnant to the context mean and include its successors in interest, representatives ' +
      'and permitted assigns) of the OTHER PART.'
    );
    doc.moveDown(0.3);
    doc.font('Helvetica-Oblique').fontSize(9.5).text('The Owner and Eightlines are individually referred to as a "Party" and collectively as the "Parties".');
    doc.moveDown(0.8);

    h1().text('1. Recitals');
    bullet('Eightlines develops technology platforms, manages fleet operations, and provides marketing and syndication services to assist vehicle owners in receiving rental bookings from Customers.');
    bullet('Eightlines operates its own proprietary platform (Ziyam Direct) and concurrently syndicates and lists vehicles on multiple third-party mobility platforms to maximize booking volume and yield for the Owner.');
    bullet('The Owner represents that they are the sole and lawful owner of the vehicle described in Annexure I (the "Vehicle"), or have been duly authorized by the lawful owner to list it and enter into this Agreement.');
    bullet('The Owner consents to make the Vehicle available to Eightlines for receiving rental bookings across Eightlines\' proprietary Platform and any associated third-party platforms Eightlines utilizes.');
    bullet('While absolute ownership, title, and interest in the Vehicle remains solely with the Owner at all times, Eightlines shall act as the exclusive Fleet Operator, relieving the Owner of the burden of directly operating, tracking, or fulfilling rental obligations.');
    bullet('All risks, responsibilities, and liabilities associated with the Vehicle remain solely vested with the Owner.');
    doc.moveDown(0.4);

    h1().text('2. Listing and Usage of the Vehicle');
    body().text('2.1. Multi-Platform Listing: the Owner authorizes Eightlines to list the Vehicle on Eightlines\' proprietary applications and websites, as well as on multiple third-party self-drive and rental platforms managed by Eightlines.');
    body().text('2.2. The Owner shall ensure the Vehicle is well maintained, in good working condition, and meets appropriate hygiene standards throughout the Term.');
    body().text('2.3. Obligations relating to upkeep, repairs, or servicing shall be undertaken solely by the Owner, who is solely responsible for ensuring compliance with all applicable laws, regulations, and permits pertaining to the Vehicle.');
    doc.moveDown(0.4);

    h1().text('3. Vehicle Ownership');
    body().text('3.1. Absolute and unencumbered ownership of the Vehicle remains with the Owner at all times. Nothing in this Agreement transfers ownership, title, or interest in the Vehicle to Eightlines or its partner platforms.');
    doc.moveDown(0.4);

    h1().text('4. Fare Collection, Fee Policy, and Taxes');
    body().text('4.1. Fare Collection: consideration for rental services ("Fare") is payable by the Customer. Eightlines acts as a limited collection agent on behalf of the Owner across all platforms, remitting payouts via electronic transfer to the Owner\'s specified bank account.');
    body().text('4.2. Operational Charges: Eightlines exclusively retains all delivery/pickup charges, fuel discrepancy fees, FASTag handling charges, and traffic violation challan recoveries. These represent operational revenue for Eightlines\' ground logistics and do not form part of the Owner\'s yield.');
    body().text('4.3. Platform Fee: Eightlines charges the Owner a Facilitation Fee within an 18-28% band of the Gross Base Fare (the exact rate for this Vehicle is confirmed in Annexure I), covering 24/7 guest support, multi-platform technology syndication, marketing, and dispatch logistics.');
    body().text('4.4. Taxes: Eightlines shall deduct applicable Tax Deducted at Source (TDS) as required by law and issue Form 16A certificates to the Owner.');
    doc.moveDown(0.4);

    h1().text('5. Roles and Obligations of the Owner');
    bullet('Maintenance: the Owner ensures the Vehicle is roadworthy, defect-free, and safety-compliant, bearing all costs of maintenance, repairs, and consumables every 10,000 km at an authorized service center, and retains itemized tax invoices as proof.');
    bullet('Documentation: the Owner provides and maintains valid RC, comprehensive own-damage and third-party insurance, and PUC certificate.');
    bullet('Security: the Owner retains at least two original vehicle keys at all times, to preserve insurance-claim validity.');
    doc.moveDown(0.4);

    h1().text('6. Roles and Obligations of Eightlines');
    bullet('Notifies the Owner of all booking requests from its own Platform and syndicated third-party platforms.');
    bullet('Facilitates accurate and timely settlement of amounts payable to the Owner, per the Payout Release Mechanism in Annexure I.');
    bullet('Provides Roadside Assistance (RSA) for vehicle recovery to a garage; does not guarantee booking volume, utilization, or revenue.');
    bullet('Bears financial responsibility for on-trip mechanical/electrical breakdowns and guest-caused damages (subject to recovery from guest protection deposits and insurance as applicable); retains no liability for breakdowns caused by the Owner\'s neglected maintenance.');
    doc.moveDown(0.4);

    h1().text('7. Eligibility of Owner and Vehicle');
    bullet('The Owner must be 18+ years of age, legally competent, and hold valid government identification.');
    bullet('The Vehicle must be registered in the Owner\'s name, under 6 years old from date of manufacture, with recorded mileage below 50,000 km.');
    bullet('The Vehicle must be fitted with a functioning dual-GPS tracking device and remote immobilizer for real-time monitoring and emergency security, with operational costs borne by the Owner.');
    doc.moveDown(0.4);

    h1().text('8. Damages, Theft, and Confiscation');
    body().text('8.1. The Owner bears any partial or total loss not recovered through the Vehicle\'s insurance coverage. If the Vehicle is impounded due to a Customer\'s actions, the Owner must secure its release at their own cost; Eightlines will assist in recovering applicable charges from the Customer using KYC records but is not liable to compensate the Owner for the confiscation itself.');
    doc.moveDown(0.4);

    h1().text('9. Limitation of Liability');
    body().text(
      '9.1. Under no circumstances will Eightlines or its directors, officers, employees, agents, or sub-contractors ' +
      'be liable to the Owner for any indirect, incidental, consequential, special, or exemplary losses arising from ' +
      'this Agreement, including loss of revenue, goodwill, or anticipated profits.'
    );
    body().text(
      '9.2. Eightlines\' total aggregate liability under this Agreement, however arising, shall be limited to an ' +
      'amount equal to 25% (twenty-five percent) of the ex-showroom price at which the Owner procured the Vehicle. ' +
      'Annexure III sets out the deemed value of the Vehicle by age for reference in any such calculation.'
    );
    doc.moveDown(0.4);

    h1().text('10. Term and Termination');
    body().text('10.1. Term: this Agreement is valid for 36 (thirty-six) months from the Effective Date and may be extended by mutual consent.');
    body().text('10.2. Termination for Convenience: either Party may terminate by providing thirty (30) days\' written notice.');
    body().text('10.3. Termination for Cause: Eightlines may terminate immediately for material breaches, regulatory violations, provision of untrue or inaccurate information, or if the Vehicle fails a physical inspection.');
    doc.moveDown(0.4);

    h1().text('11. Confidentiality and Intellectual Property');
    body().text('11.1. Both Parties shall protect confidential information (business methods, customer data, commercial terms) with reasonable care. Any use of Eightlines\' intellectual property (trademarks, software, domain names) outside the scope of this Agreement constitutes a material breach.');
    doc.moveDown(0.4);

    h1().text('12. Indemnification');
    body().text('12.1. The Owner indemnifies Eightlines against losses, damages, or claims arising from the Owner\'s willful misconduct, negligence, or breach of applicable laws. Eightlines is not liable for death, injury, or damages to the Customer or any third person arising from provisioning of services under this Agreement, beyond the limitation set out in Clause 9.');
    doc.moveDown(0.4);

    h1().text('13. Governing Law and Jurisdiction');
    body().text('13.1. This Agreement is governed by the laws of India. Courts at Bengaluru, Karnataka shall have exclusive jurisdiction over any disputes arising under this Agreement.');
    doc.moveDown(0.4);

    h1().text('14. Feedback, Assignment & Relationship Between the Parties');
    body().text('14.1. Eightlines may use, share, or display Customer feedback without attribution to the Owner. The Owner may not assign rights or obligations under this Agreement without Eightlines\' prior written consent; Eightlines may assign its rights to any affiliate or subsidiary without the Owner\'s consent.');
    body().text('14.2. This Agreement does not create a partnership, joint venture, agency, or employer-employee relationship between the Parties — it is a principal-to-principal contract between independent contractors.');
    doc.moveDown(0.4);

    h1().text('15. Survival, Waiver, Entire Agreement, Amendments & Counterparts');
    body().text(
      '15.1. Provisions intended to survive termination shall continue to apply beyond expiry. Failure to enforce any ' +
      'provision does not waive the right to enforce it later. This Agreement, with its Annexures, constitutes the ' +
      'entire understanding between the Parties on this subject and supersedes prior drafts or discussions. No ' +
      'amendment is binding unless in writing and signed by both Parties\' authorized representatives. This Agreement ' +
      'may be executed electronically (including .pdf) and in counterparts, each an original, together constituting ' +
      'one Agreement.'
    );
    doc.moveDown(1);

    // ── Annexure I ──
    doc.addPage();
    doc.font('Helvetica-Bold').fontSize(13).text('ANNEXURE I', { align: 'center' });
    doc.fontSize(11).text('Vehicle Details, Effective Date & Commercials', { align: 'center' });
    doc.moveDown(0.8);
    body().font('Helvetica-Bold').text(`Effective Date: ${data.createdAt.toLocaleDateString('en-IN')}`);
    doc.font('Helvetica-Bold').text(`Vehicle Registration: ${data.registrationNo}`);
    doc.font('Helvetica');
    [
      ['Brand', data.make],
      ['Model', data.model],
      ['Year of Manufacture', String(data.year)],
      ['Transmission', data.transmission],
      ['Fuel', data.fuelType],
      ...(data.chassisNo ? [['Chassis No.', data.chassisNo]] : []),
      ['Valid comprehensive own-damage insurance policy on file', data.hasComprehensiveInsurance ? 'Yes' : 'Pending verification'],
    ].forEach(([label, value]) => doc.text(`${label}: ${value}`));
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').fontSize(11).text('Operational Timeline & Payout Schedule (N+1 Day Policy)');
    doc.font('Helvetica').fontSize(10.5).moveDown(0.3);
    bullet('Platform Credit Windows: weekly-cycle platforms (e.g., Zoomcar) credit Eightlines weekly; fast-settlement platforms credit funds within 24-48 hours post-trip.');
    bullet('N+1 Day Release: the Owner\'s payout is released within 1 business day (24 hrs) following cleared receipt from the relevant platform.');
    bullet('Net Formula: Net Payout = Gross Base Fare − Facilitation Fee (18-28%, per Clause 4.3) − Statutory TDS (Form 16A issued).');
    bullet('Periodic Service: every 10,000 km, Owner selects an authorized service center and funds the service.');
    bullet('On-Trip Breakdown & Guest Damages: Eightlines Fleet bears initial responsibility, subject to recovery from guest deposits/insurance.');
    bullet('Doorstep Service: Eightlines retains 100% of the doorstep delivery/pickup fee.');
    doc.moveDown(0.8);

    // ── Annexure II ──
    doc.font('Helvetica-Bold').fontSize(13).text('ANNEXURE II', { align: 'center' });
    doc.fontSize(11).text('Vehicle Condition Guidelines', { align: 'center' });
    doc.moveDown(0.5);
    body().text(
      'The Owner must provide a Vehicle meeting standard roadworthiness parameters, including but not limited to: ' +
      'valid registration, insurance and PUC; functioning parking and service brakes (≥25% brake life remaining); ' +
      'an undamaged exhaust system with no visible smoke; smoothly functioning steering, suspension, and horn; ' +
      'crack-free windshield and legally tinted, crack-free windows with working wipers; engine, cooling, ' +
      'lubrication, electrical, and transmission systems in working order with no active warning lights or recalls; ' +
      'fully functioning headlights, tail lights, hazards, indicators, and mirrors; tyres with ≥50% tread depth, ' +
      'under 4 years old, and free of cuts or bulges; and functioning seatbelts and airbags with no SRS/OCS warning ' +
      'lights, hanging panels, or structural damage. The Owner undertakes to perform a thorough inspection of the ' +
      'Vehicle\'s mechanical, electrical, and safety aspects prior to the start of every booking.'
    );
    doc.moveDown(0.8);

    // ── Annexure III ──
    doc.font('Helvetica-Bold').fontSize(13).text('ANNEXURE III', { align: 'center' });
    doc.fontSize(11).text('Deemed Value of the Vehicle as per its Age', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(9.5).font('Helvetica');
    const dvTop = doc.y;
    doc.font('Helvetica-Bold').text('Age of Vehicle (from date of manufacture)', 55, dvTop, { width: 280 });
    doc.text('Deemed Value (% of ex-showroom price)', 340, dvTop, { width: 180 });
    doc.moveDown(0.4);
    doc.font('Helvetica');
    DEEMED_VALUE_TABLE.forEach(([age, pct]) => {
      const y = doc.y;
      doc.text(age, 55, y, { width: 280 });
      doc.text(pct, 340, y, { width: 180 });
    });
    doc.moveDown(0.8);

    // ── Annexure IV ──
    doc.addPage();
    doc.font('Helvetica-Bold').fontSize(13).text('ANNEXURE IV', { align: 'center' });
    doc.fontSize(11).text('Wear and Tear Not Covered Under Damage Policy', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(9).font('Helvetica-Oblique').text('The following are considered normal wear and tear, not chargeable to a Guest as damage:', { align: 'center' });
    doc.moveDown(0.5);
    doc.fontSize(9).font('Helvetica');
    WEAR_AND_TEAR_EXCLUSIONS.forEach((item, i) => {
      doc.text(`${i + 1}. ${item}`);
    });
    doc.moveDown(1);

    doc.font('Helvetica-Bold').fontSize(10.5).text('IN WITNESS WHEREOF, the Parties have executed this Agreement electronically or physically as of the Agreement Date.', { align: 'center' });
    doc.moveDown(0.3);
    doc.text('SIGNED AND DELIVERED', { align: 'center' });
    doc.moveDown(2.5);

    doc.font('Helvetica').fontSize(10);
    const sigY = doc.y;
    doc.text('_______________________', 60, sigY);
    doc.text('_______________________', 320, sigY);
    doc.text(`Owner — ${data.ownerName}`, 60);
    doc.text('For Eightlines Fleet Private Limited', 320, doc.y - doc.currentLineHeight());
    doc.fontSize(9).fillColor('#666').text(`Ph: ${data.ownerPhone}`, 60);
    doc.text(`Represented by: ${data.fleetOperatorName}`, 320);

    doc.end();
  });
}
