import PDFDocument from 'pdfkit';

interface HostOnboardingAgreementData {
  hostId: string;
  hostName: string;
  hostEmail: string;
  hostPhone: string;
  createdAt: Date;
}

/** Renders the same agreement shown at /host/agreement as a PDF buffer, for Setu eSign upload. */
export function renderHostOnboardingAgreementPdf(data: HostOnboardingAgreementData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const h1 = () => doc.font('Helvetica-Bold').fontSize(12).moveDown(0.3);
    const body = () => doc.font('Helvetica').fontSize(10.5);

    doc.font('Helvetica-Bold').fontSize(16).text('EIGHTLINES FLEET PRIVATE LIMITED', { align: 'center' });
    doc.font('Helvetica').fontSize(9).fillColor('#666').text('ZiyamSelfDrive — Bengaluru, Karnataka', { align: 'center' });
    doc.fontSize(13).font('Helvetica-Bold').fillColor('#000').text('HOST ONBOARDING AGREEMENT', { align: 'center' });
    doc.fontSize(8).font('Helvetica').fillColor('#888').text(`Agreement ID: HOA-${data.hostId.slice(0, 8).toUpperCase()}`, { align: 'center' });
    doc.moveDown(1).fillColor('#000');

    doc.fontSize(8.5).font('Helvetica-Oblique').fillColor('#555').text(
      'This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder ' +
      'as applicable, along with the amended provisions pertaining to electronic records in various statutes. This ' +
      'electronic record is generated by a computer system and does not require physical signatures.'
    );
    doc.moveDown(0.8).fillColor('#000').fontSize(10.5).font('Helvetica');

    doc.text(
      `This Host Onboarding Agreement ("Agreement") is made and effective as of ${data.createdAt.toLocaleDateString('en-IN')} ` +
      '("Effective Date").'
    );
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').text('BETWEEN', { align: 'center' });
    body().text(
      'Eightlines Fleet Private Limited, operating the ZiyamSelfDrive platform (hereinafter referred to as the ' +
      '"Company", "Ziyam", or "Platform"), of the ONE PART;'
    );
    doc.moveDown(0.4);
    doc.font('Helvetica-Bold').text('AND', { align: 'center' });
    body().text(
      `${data.hostName} (hereinafter referred to as the "Host"), which expression shall, unless repugnant to the ` +
      `context or meaning thereof, be deemed to include his/her heirs, legal representatives, and permitted assigns, ` +
      `of the OTHER PART.`
    );
    doc.moveDown(0.3);
    doc.font('Helvetica-Oblique').fontSize(9.5).text('(The Company and the Host shall be hereinafter collectively referred to as the "Parties" and individually as the "Party").');
    doc.moveDown(0.8);

    h1().text('WHEREAS');
    body();
    doc.text('a. The Company operates ZiyamSelfDrive, a peer-to-peer self-drive vehicle rental marketplace currently operating in Bengaluru, connecting vehicle owners ("Hosts") with renters ("Guests").');
    doc.text('b. The Host wishes to list one or more vehicles on the Platform and receive booking requests from Guests.');
    doc.text('c. The Company acts as a limited payment collection and facilitation agent — collecting fares from Guests via its payment partner and remitting the Host\'s share as set out in this Agreement.');
    doc.text('d. This Agreement is a one-time, account-level agreement between the Host and the Company, and applies regardless of whether a given vehicle is Self-Hosted or Fleet-Managed (each as defined below).');
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').fontSize(9.5).text('NOW, THEREFORE, IN CONSIDERATION OF THE FOREGOING AND THE COVENANTS AND CONDITIONS CONTAINED HEREIN, THE PARTIES HEREBY AGREE AS FOLLOWS:');
    doc.moveDown(0.8);

    h1().text('1. Two Modes of Hosting');
    body();
    doc.text('1.1. Self-Hosted: the Host retains full control of the vehicle — setting price within the Platform\'s market-rate band, handling Guest handovers directly, and receiving payouts directly to their linked bank account.');
    doc.text('1.2. Fleet-Managed: the Host may separately opt a specific vehicle into fleet management, under which a Ziyam-assigned Fleet Operator handles guest handovers, cleaning, and day-to-day logistics for that vehicle. Fleet-Managed vehicles require an additional, vehicle-specific Fleet Partner Agreement before going live, which is layered on top of (and does not replace) this Agreement.');
    doc.moveDown(0.6);

    h1().text('2. Revenue Share');
    body().text('2.1. The Host retains 70% (seventy percent) of the base fare of every completed booking. The Company\'s commission is 30% (thirty percent), covering payment processing, guest verification, marketing, dynamic pricing infrastructure, and platform support. This split applies equally to Self-Hosted and Fleet-Managed vehicles.');
    doc.moveDown(0.6);

    h1().text('3. Payout Timeline ("N+1" Policy)');
    body();
    doc.text('3.1. Self-Hosted vehicles: the Host\'s payout is released 24-48 hours after trip completion (the "settlement window", which the Company may adjust from time to time), or bundled into a fixed weekly payout run if the Host opts into weekly settlement from their dashboard.');
    doc.text('3.2. Fleet-Managed vehicles: the Host\'s payout is released within 1 (one) business day of the assigned Fleet Operator confirming receipt of cleared funds from the Platform for that booking.');
    doc.text('3.3. No advance or estimated payouts are made without a cleared, confirmed receipt. This protects both the Host and the Company from chargebacks and payment reversals.');
    doc.text('3.4. Payouts are released only to a bank account that has been verified by the Company\'s banking partner (penny-drop verification). Unverified accounts will not receive funds.');
    doc.moveDown(0.6);

    h1().text('4. Vehicle Eligibility & Documentation');
    body();
    doc.text('4.1. Every listed vehicle must be roadworthy, mechanically sound, hygiene-compliant, and carry a valid Registration Certificate (RC) in the Host\'s name (or with written authorization to list), a valid Pollution Under Control (PUC) certificate, and an active comprehensive insurance policy.');
    doc.text('4.2. The Host warrants that all documents and vehicle details submitted to the Platform are true, accurate, and current, and undertakes to promptly update the Platform upon any change (renewal, transfer, cancellation) affecting these documents.');
    doc.moveDown(0.6);

    h1().text('5. Insurance & Damage — No Platform Insurance');
    body().text('5.1. The Company is a marketplace, not an insurer, and does not provide vehicle damage insurance. The Host\'s own comprehensive insurance policy is the primary coverage for the vehicle at all times.');
    doc.text('5.2. Guest-caused damage is recovered from the Guest\'s security deposit first. Costs beyond the deposit are the Host\'s responsibility to pursue directly from the Guest; the Company will assist with claim coordination and will attempt to contribute up to ₹20,000 towards a valid claim, on a best-effort basis and not as a guaranteed indemnity.');
    doc.text('5.3. 24/7 roadside assistance (RSA) for breakdowns and abandoned-vehicle recovery is included for every Host, regardless of protection plan or hosting mode.');
    doc.moveDown(0.6);

    h1().text('6. Host Conduct & KYC');
    body();
    doc.text('6.1. The Host must complete identity verification (KYC) via DigiLocker/Aadhaar before any vehicle can go live, and must keep contact and bank details current.');
    doc.text('6.2. The Host agrees not to circumvent the Platform by arranging a rental directly with a Guest introduced through the Platform to avoid Platform fees; doing so voids KYC protection, insurance-relevant driver verification, and Platform support for that trip.');
    doc.moveDown(0.6);

    h1().text('7. Term & Termination');
    body().text('7.1. This Agreement remains in effect for as long as the Host maintains an active account on the Platform. Either Party may terminate this Agreement at any time by written notice; termination does not affect obligations (including payout of amounts already earned) accrued before the effective date of termination.');
    doc.moveDown(0.6);

    h1().text('8. Confidentiality & Intellectual Property');
    body().text('8.1. Both Parties agree to keep confidential any non-public business information exchanged under this Agreement. The Company\'s trademarks, software, and platform technology remain its exclusive property; the Host is granted no rights therein beyond using the Platform as intended.');
    doc.moveDown(0.6);

    h1().text('9. Indemnification & Limitation of Liability');
    body().text('9.1. The Host indemnifies the Company against losses, damages, or claims arising from the Host\'s willful misconduct, negligence, or breach of Applicable Laws. The Company is not liable for indirect, incidental, or consequential damages, or loss of anticipated revenue, arising from this Agreement.');
    doc.moveDown(0.6);

    h1().text('10. Governing Law & Jurisdiction');
    body().text('10.1. This Agreement is governed by the laws of India. Courts at Bengaluru, Karnataka shall have exclusive jurisdiction over any disputes arising out of or in connection with this Agreement.');
    doc.moveDown(0.6);

    h1().text('11. Entire Agreement & Amendments');
    body().text('11.1. This Agreement, together with the Platform\'s published Host Policy and (where applicable) the vehicle-specific Fleet Partner Agreement, constitutes the entire understanding between the Parties regarding Host onboarding, superseding any prior discussions on the same subject. The Company may update this Agreement from time to time by posting a revised version and notifying the Host; continued use of the Platform after such notice constitutes acceptance.');
    doc.moveDown(1);

    doc.font('Helvetica-Bold').fontSize(10.5).text('IN WITNESS WHEREOF, the Parties have executed this Agreement electronically or physically as of the Effective Date.', { align: 'center' });
    doc.moveDown(0.3);
    doc.text('SIGNED AND DELIVERED', { align: 'center' });
    doc.moveDown(2.5);

    doc.font('Helvetica').fontSize(10);
    const sigY = doc.y;
    doc.text('_______________________', 60, sigY);
    doc.text('_______________________', 320, sigY);
    doc.text('For Eightlines Fleet Private Limited', 60);
    doc.text(`Host — ${data.hostName}`, 320, doc.y - doc.currentLineHeight());
    doc.fontSize(9).fillColor('#666').text(`Ph: ${data.hostPhone}`, 320);
    doc.text(`Email: ${data.hostEmail}`, 320);

    doc.end();
  });
}
