import PDFDocument from 'pdfkit';

interface LeaseAgreementData {
  bookingId: string;
  createdAt: Date;
  hostName: string;
  guestName: string;
  guestPhone?: string;
  registrationNo: string;
  chassisNo?: string | null;
  make: string;
  model: string;
  year: number;
  startTime: Date;
  endTime: Date;
  protectionPlan: string;
  totalAmount: number;
  securityDeposit: number;
}

const PENALTY_SCHEDULE: [string, string][] = [
  ['Unauthorized Driver / Handover to Third Party', '₹10,000/- + Immediate Termination'],
  ['Tampering with Dashcam or OBD Port (GPS)', '₹12,500/-'],
  ['Loss of or Damage to Vehicle Keys', '₹10,000/- + lock system cost (up to ₹75,000)'],
  ['Loss of Original Vehicle Documents', '₹10,000/-'],
  ['Overspeeding (above 100 km/h)', '₹2,500/- per instance'],
  ['Harsh Braking (>3 instances per 5km after a 2km grace period, telematics-tracked)', '₹1,000/-'],
  ['Rapid Acceleration / Rash Driving (>3 instances per 5km after a 2km grace period)', '₹2,000/-'],
  ['DUI / Reckless Driving', '100% of all costs + legal action'],
  ['Smoking or Alcohol Consumption inside Vehicle', '₹1,250/-'],
  ['Exterior Washing Required (dirt/mud)', '₹500/-'],
  ['Interior Cleaning (spills, stains, trash)', '₹700/- to ₹1,500/- (severity-based)'],
];

/** Renders the same lease agreement shown at /bookings/:id/agreement as a PDF buffer, for Setu eSign upload. */
export function renderLeaseAgreementPdf(data: LeaseAgreementData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, bufferPages: true });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const h1 = () => doc.font('Helvetica-Bold').fontSize(12).moveDown(0.3);
    const body = () => doc.font('Helvetica').fontSize(10.5);

    doc.font('Helvetica-Bold').fontSize(16).text('EIGHTLINESFLEET', { align: 'center' });
    doc.font('Helvetica').fontSize(9).fillColor('#666').text('Vehicle Rental Services — Bengaluru, Karnataka', { align: 'center' });
    doc.fontSize(13).font('Helvetica-Bold').fillColor('#000').text('LEASE AGREEMENT FOR CAR SHARING', { align: 'center' });
    doc.fontSize(8).font('Helvetica').fillColor('#888').text(`Agreement ID: LA-${data.bookingId.slice(0, 8).toUpperCase()}`, { align: 'center' });
    doc.moveDown(1).fillColor('#000');

    doc.fontSize(8.5).font('Helvetica-Oblique').fillColor('#555').text(
      'This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder ' +
      'as applicable, along with the amended provisions pertaining to electronic records in various statutes. This ' +
      'electronic record is generated by a computer system and does not require physical signatures. This Agreement ' +
      'is also subject to the Indian Contract Act, 1872 and the Digital Personal Data Protection Act, 2023 insofar as ' +
      'it involves the collection and processing of KYC documents, GPS/telematics data, and trip records.'
    );
    doc.moveDown(0.8).fillColor('#000').fontSize(10.5).font('Helvetica');

    doc.text(
      'This lease agreement between the Host and Guest records the terms and conditions regarding the lease of the ' +
      'vehicle by the Host to the Guest. This lease agreement adheres to the provisions outlined in Section 51 of ' +
      'the Motor Vehicles Act, 1988, recognizing leasing, hire-purchase, and hypothecation of vehicles for personal use.'
    );
    doc.moveDown(0.6);
    doc.text(
      `This Lease Agreement for Car Sharing is made and effective from ("Effective Date" or the "Booking Start ` +
      `Date") ${data.startTime.toLocaleString('en-IN')} to End date ${data.endTime.toLocaleString('en-IN')}, as ` +
      `reflected in the booking details on the App (the "Agreement").`
    );
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').text('BETWEEN', { align: 'center' });
    body().text(
      `${data.hostName} (hereinafter referred to as the "Host" or "Lessor"), which expression shall, unless ` +
      `repugnant to the context or meaning thereof, be deemed to include his/her heirs, legal representatives, and ` +
      `permitted assigns, of the ONE PART;`
    );
    doc.moveDown(0.4);
    doc.font('Helvetica-Bold').text('AND', { align: 'center' });
    body().text(
      `${data.guestName} (hereinafter referred to as the "Guest" or "Lessee"), which expression shall, unless ` +
      `repugnant to the context or meaning thereof, be deemed to include his/her heirs, legal representatives, and ` +
      `permitted assigns, of the OTHER PART.`
    );
    doc.moveDown(0.3);
    doc.font('Helvetica-Oblique').fontSize(9.5).text('(The Host and the Guest shall be hereinafter collectively referred to as the "Parties" and individually as the "Party").');
    doc.moveDown(0.8);

    h1().text('WHEREAS');
    body();
    doc.text(`a. The Host is the sole legal, beneficial, and registered owner of the vehicle bearing registration number ${data.registrationNo}${data.chassisNo ? ` with Chassis No. ${data.chassisNo}` : ''} ("Vehicle").`);
    doc.text('b. The Host has listed the Vehicle for leasing on the Platform (defined below) subject to the terms and conditions specified therein.');
    doc.text(`c. The Guest, a user of the Platform, has placed a request through the Platform/App for the lease of the Vehicle, bearing booking id — ${data.bookingId}`);
    doc.text('d. The Lessor is willing to lease the Vehicle to the Guest, subject to the terms and conditions of this Agreement and the policies stipulated upon the Platform.');
    doc.moveDown(0.5);
    doc.font('Helvetica-Bold').fontSize(9.5).text('NOW, THEREFORE, IN CONSIDERATION OF THE FOREGOING AND THE COVENANTS AND CONDITIONS CONTAINED HEREIN, THE PARTIES HEREBY AGREE AS FOLLOWS:');
    doc.moveDown(0.8);

    h1().text('1. Definitions and Interpretation');
    body();
    doc.text('1.1. "Applicable Laws" means all statutes, including the Motor Vehicles Act, 1988 ("MVA"), and rules made thereunder.');
    doc.text('1.2. "Permitted Territory" shall mean the territory of India, excluding Ladakh and foreign countries (Nepal, Bhutan, etc.).');
    doc.text('1.3. "Prohibited Use" includes commercial usage, racing, rallying, or usage by any person other than the Lessee.');
    doc.moveDown(0.6);

    h1().text('2. Grant of Lease and Possession');
    body();
    doc.text('2.1. The Lessor hereby grants the Lessee a lease of the Vehicle for the Booking Period defined in the App.');
    doc.text('2.2. The Lessee acknowledges that this Agreement constitutes a transfer of possession and control of the Vehicle for the lease period, but not ownership. The Lessor remains the registered owner.');
    doc.moveDown(0.6);

    h1().text('3. Strict Usage Policy & Unauthorized Drivers');
    body();
    doc.text('3.1. Personal Use Only: The Vehicle is strictly for the personal use of the Lessee.');
    doc.text('3.2. Authorized Driver: The Vehicle must be driven ONLY by the Lessee named in this Agreement.');
    doc.text('3.3. Prohibition on Sub-Leasing: Handing over the vehicle to any third party (friends, family, or unregistered drivers) is strictly prohibited.');
    doc.moveDown(0.4);
    doc.font('Helvetica-Bold').fillColor('#a00').text('PENALTY: If the Vehicle is found to be driven by anyone other than the Lessee, a non-negotiable penalty of ₹10,000/- (Rupees Ten Thousand Only) shall be levied immediately, and the lease shall be terminated.');
    doc.fillColor('#000');
    doc.moveDown(0.4);
    body().text(
      "The vehicle shall be driven exclusively by the Lessee. Driving by any unauthorized individual or transfer of " +
      "the vehicle to a third party is strictly prohibited. The Lessee's driver details are verified via the " +
      "Platform's KYC process (DigiLocker / Aadhaar-based verification), and the insurance policy is issued based " +
      "on the verified driver information. In the event of any damage or incident, insurance claims may be denied " +
      "if the vehicle is operated by a person other than the authorized Lessee."
    );
    doc.moveDown(0.6);

    h1().text('4. Schedule of Penalties & Liquidated Damages');
    body().text('The Lessee acknowledges that the following amounts are agreed pre-estimates of damages and costs incurred by the Lessor for violations. The Lessee agrees to pay these immediately upon demand:');
    doc.moveDown(0.3);
    doc.fontSize(9);
    PENALTY_SCHEDULE.forEach(([label, amount]) => {
      const y = doc.y;
      doc.font('Helvetica').text(`• ${label}`, 55, y, { width: 340, continued: false });
      doc.font('Helvetica-Bold').text(amount, 400, y, { width: 150, align: 'right' });
    });
    doc.fontSize(10.5);
    doc.moveDown(0.6);

    h1().text('5. Vehicle Integrity & Equipment');
    body();
    doc.text('5.1. Dashcam & GPS: The Lessee agrees not to obstruct, unplug, or tamper with the Dashcam or On-Board Diagnostics (OBD) port. Tampering is considered a malicious attempt to hide vehicle misuse and attracts the fine mentioned in Clause 4.');
    doc.text('5.2. Documents: The Lessee acknowledges receipt of original or certified copies of the RC, Insurance, and PUC. Loss of these documents attracts the penalty mentioned above.');
    doc.moveDown(0.6);

    h1().text('6. Insurance & Liability');
    body();
    doc.text('6.1. Third-Party Liability: The Lessor maintains insurance strictly for Third-Party Liability as required by the MVA.');
    doc.text('6.2. Lessee\'s Liability (Own Damage): The Lessee is 100% financially liable for: any damage to the Vehicle ("Own Damage") during the lease term; theft of the Vehicle if caused by negligence (e.g., leaving keys in the car); and any claims denied by the insurance company due to the Lessee\'s intoxication, lack of valid license, or violation of traffic rules.');
    doc.moveDown(0.6);

    h1().text('7. Security Deposit');
    body().text(
      `A refundable security deposit of ₹${data.securityDeposit.toLocaleString('en-IN')} has been collected via the ` +
      'Platform and is held in escrow. It shall be released to the Guest after a clean return of the Vehicle, less ' +
      'any deductions for damages, penalties, or charges due under this Agreement, in accordance with the ' +
      'Platform\'s published Refund & Cancellation Policy.'
    );
    doc.moveDown(0.6);

    h1().text('8. Return of Vehicle');
    body();
    doc.text('8.1. The Lessee shall return the vehicle in the same condition as received.');
    doc.text('8.2. Fuel Policy: The vehicle must be returned with the same fuel level. Shortage is charged at ₹100 per 10km-equivalent shortage; excess fuel is non-refundable.');
    doc.moveDown(0.6);

    h1().text('9. Indemnity');
    body().text("The Lessee agrees to indemnify and hold the Lessor harmless against any claims, fines (challans), or legal actions arising from the Lessee's use of the Vehicle during the Lease Term.");
    doc.moveDown(0.6);

    h1().text('10. Governing Law & Dispute Resolution');
    body().text(
      'This Agreement shall be governed by and construed in accordance with the laws of India. Subject to the ' +
      "Platform's grievance redressal process, the courts at Bengaluru, Karnataka shall have exclusive jurisdiction " +
      'over any disputes arising out of or in connection with this Agreement.'
    );
    doc.moveDown(1);

    doc.font('Helvetica-Bold').fontSize(10.5).text('IN WITNESS WHEREOF, the Parties have executed this Agreement electronically or physically as of the Effective Date.', { align: 'center' });
    doc.moveDown(0.3);
    doc.text('SIGNED AND DELIVERED', { align: 'center' });
    doc.moveDown(2.5);

    doc.font('Helvetica').fontSize(10);
    const sigY = doc.y;
    doc.text('_______________________', 60, sigY);
    doc.text('_______________________', 320, sigY);
    doc.text(`Host / Lessor — ${data.hostName}`, 60);
    doc.text(`Guest / Lessee — ${data.guestName}`, 320, doc.y - doc.currentLineHeight());
    if (data.guestPhone) doc.fontSize(9).fillColor('#666').text(`Ph: ${data.guestPhone}`, 320);

    doc.moveDown(1.5).fillColor('#000').fontSize(9).font('Helvetica-Bold').text('Booking Summary', 50, doc.y);
    doc.font('Helvetica').fontSize(9);
    [
      ['Booking ID', data.bookingId],
      ['Vehicle', `${data.make} ${data.model} (${data.year})`],
      ['Registration No.', data.registrationNo],
      ...(data.chassisNo ? [['Chassis No.', data.chassisNo]] : []),
      ['Start Date & Time', data.startTime.toLocaleString('en-IN')],
      ['End Date & Time', data.endTime.toLocaleString('en-IN')],
      ['Protection Plan', data.protectionPlan],
      ['Total Amount', `₹${data.totalAmount.toLocaleString('en-IN')}`],
    ].forEach(([label, value]) => doc.text(`${label}: ${value}`));

    doc.end();
  });
}
