// PLACEHOLDER — generated by hand, not by `flutterfire configure`.
//
// This file exists only so the project compiles before Firebase is wired
// up. Every value below is a non-functional placeholder. Run
// `flutterfire configure` against the same Firebase project as
// src/frontend (see specs/001-flutter-renter-app/contracts/firebase-ai-itinerary.md
// and tasks.md T004) to regenerate this file for real — it will overwrite
// this stub. Nothing outside the itinerary-AI feature (data/itinerary/itinerary_ai_service.dart)
// depends on these values being real; auth, fleet browse, booking, and
// profile all work without Firebase.
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show TargetPlatform, defaultTargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform — '
          'run `flutterfire configure`.',
        );
    }
  }

  static const android = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'REPLACE_ME',
    storageBucket: 'REPLACE_ME',
    iosBundleId: 'in.ziyam.mobile',
  );
}
